project:
  type: website

website:
  title: "{{< fa home >}}"
  navbar:
    background: primary
    left:
      - text: "Composition API"
        href: migration-dashboard.qmd
      - text: "Typescript"
        href: typescript-dashboard.qmd
      - text: "Tailwind {{< fa flask >}}"
        href: tailwind-migration.qmd
      - text: "Testing Library {{< fa flask >}}"
        href: testing-library-migration.qmd
      - text: "Pinia"
        href: pinia-migration.qmd

format:
  html:
    theme:
      light: materia
      dark: superhero
    respect-user-color-scheme: true
  dashboard:
    theme:
      light: materia
      dark: superhero
    respect-user-color-scheme: true
