project:
  type: website

website:
  title: "Migrations"
  navbar:
    background: primary
    left:
      - text: "Composition API"
        href: migration-dashboard.qmd
      - text: "Typescript"
        href: typescript-dashboard.qmd
      - text: "Tailwind"
        href: tailwind-migration.qmd
      - text: "Testing Library"
        href: testing-library-migration.qmd
      - text: "Pinia"
        href: pinia-migration.qmd

format:
  html:
    theme:
      light: materia
      dark: darkly
    respect-user-color-scheme: true
  dashboard:
    theme:
      light: materia
      dark: darkly
    respect-user-color-scheme: true
